import {Button, Heading, Text} from '@chakra-ui/react';
import Head from 'next/head';
import {useAuth} from '../lib/auth';

export default function Home() {
	const auth = useAuth();
	return (
		<div>
			<Head>
				<title>Nextjs project</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<Heading>Code of saturday tonight</Heading>

				{!auth?.user?.email && (
					<Button onClick={e => auth.signinWithGitHub()}>Sign In</Button>
				)}
				<Text>Current user: {auth?.user?.email}</Text>
				{auth?.user?.email && (
					<Button onClick={e => auth.signout()}>Sign Out</Button>
				)}
			</main>
		</div>
	);
}
